In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/pump_test.csv')
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,other,other
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,other,other
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,unknown,soft,good,dry,dry,shallow well,shallow well,groundwater,other,other
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

In [3]:
others = ['d5881dc8-2ca7-4ca6-82db-b67960ae93c6-stepthom_submission.csv',
          '0baf47ac-3395-4a2b-8dc1-6e56fdc05209-stepthom_submission.csv',
          'f06f31fa-e145-42f5-8a77-dd7a0818e747-stepthom_submission.csv',
          #'9ac1099b-baa8-406d-8e1a-9b4fd2bfa470-stepthom_submission.csv',
          
          
          
          'bab2166e-66ae-4e2a-85a2-fbb7d916e680-stepthom_submission.csv',
          'f18637f2-699e-47cd-b55d-0e8acdd1d2c8-stepthom_submission.csv',
          'ak_100_None_30_15-stepthom_submission.csv'
          #'-stepthom_submission.csv',
          #'-stepthom_submission.csv',
          
         ]

p = 0
for other in others:
    _df = pd.read_csv('out/' + other)
    df['p' + str(p)] = _df.status_group
    p = p + 1
    
pcols = ["p{}".format(i) for i in range(p)]

In [4]:
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,source_type,source_class,waterpoint_type,waterpoint_type_group,p0,p1,p2,p3,p4,p5
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,rainwater harvesting,surface,other,other,non functional,non functional,functional,functional,functional,functional
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,spring,groundwater,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,rainwater harvesting,surface,other,other,functional,functional,functional,functional,functional,functional
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,shallow well,groundwater,other,other,non functional,non functional,non functional,non functional,non functional,non functional
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,spring,groundwater,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional

In [5]:
df.loc[~(df['p0'] == df['p1'])]

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,source_type,source_class,waterpoint_type,waterpoint_type_group,p0,p1,p2,p3,p4,p5
6,24806,0.0,2011-03-02,Government Of Tanzania,550,Gover,36.398041,-7.541382e+00,none,0,...,borehole,groundwater,hand pump,hand pump,non functional,functional,non functional,non functional,non functional,non functional
32,42658,0.0,2012-11-05,Tlc,0,TLC,33.124534,-4.857669e+00,Shuleni,0,...,shallow well,groundwater,hand pump,hand pump,functional,non functional,functional,functional,functional,non functional
95,25872,0.0,2012-10-18,World Vision,0,Consuting Engineer,32.996930,-4.193228e+00,Mwembeni,0,...,shallow well,groundwater,hand pump,hand pump,functional,non functional,non functional,non functional,non functional,functional
147,55647,0.0,2012-10-12,Dwsp,0,DWSP,32.970982,-3.733659e+00,Segerea,0,...,shallow well,groundwater,hand pump,hand pump,non functional,functional,functional,functional,functional,non functional
250,3398,0.0,2013-01-18,Rwssp,0,DWE,0.000000,-2.000000e-08,Bulyaheke,0,...,shallow well,groundwater,hand pump,hand pump,functional,functional needs repair,functional needs repair,functional needs repair,functional,functional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14666,57195,0.0,2011-04-08,Government Of Tanzania,0,Government,33.485154,-7.144926e+00,Reuben,0,...,shallow well,groundwater,hand pump,hand pump,functional,non functional,functional,non functional,functional,functional
14714,59505,0.0,2011-04-03,NaN,0,NaN,34.303140,-8.678767e+00,Kwa Mwaliayo,0,...,river/lake,surface,communal standpipe,communal standpipe,non functional,functional,non functional,functional,functional,functional
14741,51268,0.0,2011-07-27,Government Of Tanzania,0,DWE,30.904361,-1.212966e+00,Kwaoskali,0,...,spring,groundwater,communal standpipe,communal standpipe,non functional,functional,non functional,functional,functional needs repair,functional
14761,73255,0.0,2011-03-24,Private,51,Private,39.172799,-7.148775e+00,Kwa Ally Mahunge,0,...,shallow well,groundwater,hand pump,hand pump,non functional,functional,non functional,non functional,functional,non functional
14827,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,shallow well,groundwater,hand pump,hand pump,functional,non functional,functional,non functional,functional,functional

In [6]:
def matches(row):
    count = 0
    for c in pcols:
        if c != 'p0' and row['p0'] == row[c]:
            count = count+1
    return count

df['p0_matches'] = df.apply(matches, axis=1)

In [7]:
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,source_class,waterpoint_type,waterpoint_type_group,p0,p1,p2,p3,p4,p5,p0_matches
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,surface,other,other,non functional,non functional,functional,functional,functional,functional,1
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,groundwater,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,surface,other,other,functional,functional,functional,functional,functional,functional,5
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,groundwater,other,other,non functional,non functional,non functional,non functional,non functional,non functional,5
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,groundwater,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5

In [8]:
df.p0_matches.describe()

count    14850.000000
mean         4.728215
std          0.688508
min          0.000000
25%          5.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: p0_matches, dtype: float64

In [9]:
df.p0_matches.value_counts()

5    12050
4     2114
3      348
2      178
1      108
0       52
Name: p0_matches, dtype: int64

In [10]:
def get_label(row):
    if row['p0'] == row['p1']:
        return row['p0']
    if row['p0_matches'] >= 2:
        return row['p0']
    else:
        return row['p1']

In [11]:
df['status_group'] = df.apply(get_label, axis=1)
df.head(40)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,waterpoint_type,waterpoint_type_group,p0,p1,p2,p3,p4,p5,p0_matches,status_group
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696e+00,Dinamu Secondary School,0,...,other,other,non functional,non functional,functional,functional,functional,functional,1,non functional
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214e+00,Kimnyak,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344e+00,Puma Secondary,0,...,other,other,functional,functional,functional,functional,functional,functional,5,functional
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672e+00,Kwa Mzee Pange,0,...,other,other,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-1.095041e+01,Kwa Mzee Turuka,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
5,52449,0.0,2013-03-04,Government Of Tanzania,1685,DWE,36.685279,-3.302420e+00,Masaga,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
6,24806,0.0,2011-03-02,Government Of Tanzania,550,Gover,36.398041,-7.541382e+00,none,0,...,hand pump,hand pump,non functional,functional,non functional,non functional,non functional,non functional,4,non functional
7,28965,0.0,2013-01-25,Finw,234,FinW,39.607420,-1.089379e+01,Kwa Mkwaa,0,...,communal standpipe multiple,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
8,36301,30.0,2013-01-23,Unicef,584,LGA,39.262951,-1.082359e+01,Kwa Mzee Mpini,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
9,54122,0.0,2013-03-18,Lawatefuka Water Supply,1083,Lawatefuka water sup,37.096108,-3.251754e+00,Kwa Flora Daud,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
10,419,5.0,2013-10-03,Germany Republi,1259,CES,37.233248,-3.241121e+00,Kwa Anna P Muro,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
11,45750,0.0,2013-02-27,World Vision,608,World vision,37.686392,-4.555975e+00,Shuleni,0,...,other,other,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
12,653,0.0,2012-10-11,World Bank,0,Building works company Ltd,33.661074,-4.165720e+00,Kwa Nzega,0,...,communal standpipe multiple,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
13,14017,0.0,2011-07-29,Ministry Of Water,0,DWE,33.007680,-3.209529e+00,Gati La Shuleni,0,...,communal standpipe multiple,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
14,44607,1000.0,2011-03-02,Danida,1625,DANID,35.615624,-7.870290e+00,none,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
15,40228,1200.0,2013-06-03,Danida,916,DWE,35.482886,-1.091260e+01,Kwa Daniela,0,...,communal standpipe multiple,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
16,27714,0.0,2011-02-24,NaN,-39,NaN,39.850190,-7.727946e+00,Kitotoni,0,...,hand pump,hand pump,functional,functional,functional,functional,functional,functional,5,functional
17,28785,200.0,2011-03-11,Government Of Tanzania,1793,DWE,38.254024,-4.565802e+00,Magagai Hospital,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
18,28330,0.0,2012-10-06,Rural Water Supply And Sanitat,0,DWE,31.586798,-3.387808e+00,Shule Ya Msingi Ikuzi,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
19,18532,0.0,2013-02-02,Finw,368,FinW,39.438526,-1.058337e+01,Liponde A,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,functional,4,non functional
20,69961,0.0,2013-03-12,0,-27,0,39.322307,-6.850262e+00,Shuleni,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
21,55083,0.0,2011-03-07,Dwe,1674,DWE,34.943620,-9.352515e+00,none,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,functional,4,non functional
22,8691,0.0,2013-02-04,Tasaf,1087,DWE,31.046088,-5.054196e+00,Kwa Yorodan,0,...,other,other,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
23,30331,0.0,2013-02-09,NaN,1441,NaN,34.621048,-5.165926e+00,Andrea,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
24,70970,0.0,2012-10-07,Mwanashila,0,DWE,33.722359,-3.047122e+00,Toyekukoya Groups,0,...,hand pump,hand pump,functional,functional,functional,functional,functional,functional,5,functional
25,61136,200.0,2011-02-23,Tz Japan,1726,DWE,34.929592,-9.152872e+00,Kwa Tega,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
26,28799,0.0,2013-02-18,Germany,986,DWE,35.424443,-1.057969e+01,Shule Ya Msingi Mapo,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
27,46825,0.0,2011-04-10,Water,0,MWE &,35.894877,-6.147522e+00,Kwa Mbogambi,0,...,communal standpipe multiple,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
28,44718,0.0,2013-02-04,Dwsp,0,DWE,0.000000,-2.000000e-08,Nkubanija,0,...,hand pump,hand pump,functional needs repair,functional needs repair,functional needs repair,functional needs repair,functional needs repair,functional needs repair,5,functional needs repair
29,37350,0.0,2013-02-20,Bffs,1309,BFFS,36.291761,-5.242313e+00,Zahanati,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
30,65738,5.0,2013-12-03,Private Individual,1564,Dmdd,35.612417,-3.351168e+00,Bado,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
31,3271,0.0,2012-10-29,Government Of Tanzania,0,DWE,32.861782,-3.928199e+00,Gati La Selemi,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
32,42658,0.0,2012-11-05,Tlc,0,TLC,33.124534,-4.857669e+00,Shuleni,0,...,hand pump,hand pump,functional,non functional,functional,functional,functional,non functional,3,functional
33,67523,20.0,2013-03-13,Private Individual,1537,Dmdd,35.665075,-3.347709e+00,Kwa Matambi,0,...,communal standpipe multiple,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
34,37034,500.0,2011-03-27,Unicef,1489,DWE,34.721991,-8.862532e+00,Shuleni,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
35,42432,500.0,2011-07-04,Unicef,1798,DWE,34.705343,-9.139496e+00,Kwa Batweli Fute,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
36,27420,0.0,2011-03-14,Mkinga Distric Coun,0,DWE,38.837137,-4.775584e+00,Kibanga,0,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
37,707,1000.0,2013-02-22,Government Of Tanzania,1642,Central govt,37.658081,-3.723862e+00,Kwa Juma Sadick,3,...,communal standpipe,communal standpipe,functional,functional,functional,functional,functional,functional,5,functional
38,48489,0.0,2011-02-27,Nethalan,362,DWE,37.476322,-6.283313e+00,Shuleni,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional
39,51008,0.0,2011-03-30,Danida,0,DANIDA,33.326034,-8.881286e+00,Wangu Simanyana,0,...,communal standpipe,communal standpipe,non functional,non functional,non functional,non functional,non functional,non functional,5,non functional

In [12]:
df.loc[~(df['p0'] == df['p1'])]

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,waterpoint_type,waterpoint_type_group,p0,p1,p2,p3,p4,p5,p0_matches,status_group
6,24806,0.0,2011-03-02,Government Of Tanzania,550,Gover,36.398041,-7.541382e+00,none,0,...,hand pump,hand pump,non functional,functional,non functional,non functional,non functional,non functional,4,non functional
32,42658,0.0,2012-11-05,Tlc,0,TLC,33.124534,-4.857669e+00,Shuleni,0,...,hand pump,hand pump,functional,non functional,functional,functional,functional,non functional,3,functional
95,25872,0.0,2012-10-18,World Vision,0,Consuting Engineer,32.996930,-4.193228e+00,Mwembeni,0,...,hand pump,hand pump,functional,non functional,non functional,non functional,non functional,functional,1,non functional
147,55647,0.0,2012-10-12,Dwsp,0,DWSP,32.970982,-3.733659e+00,Segerea,0,...,hand pump,hand pump,non functional,functional,functional,functional,functional,non functional,1,functional
250,3398,0.0,2013-01-18,Rwssp,0,DWE,0.000000,-2.000000e-08,Bulyaheke,0,...,hand pump,hand pump,functional,functional needs repair,functional needs repair,functional needs repair,functional,functional,2,functional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14666,57195,0.0,2011-04-08,Government Of Tanzania,0,Government,33.485154,-7.144926e+00,Reuben,0,...,hand pump,hand pump,functional,non functional,functional,non functional,functional,functional,3,functional
14714,59505,0.0,2011-04-03,NaN,0,NaN,34.303140,-8.678767e+00,Kwa Mwaliayo,0,...,communal standpipe,communal standpipe,non functional,functional,non functional,functional,functional,functional,1,functional
14741,51268,0.0,2011-07-27,Government Of Tanzania,0,DWE,30.904361,-1.212966e+00,Kwaoskali,0,...,communal standpipe,communal standpipe,non functional,functional,non functional,functional,functional needs repair,functional,1,functional
14761,73255,0.0,2011-03-24,Private,51,Private,39.172799,-7.148775e+00,Kwa Ally Mahunge,0,...,hand pump,hand pump,non functional,functional,non functional,non functional,functional,non functional,3,non functional
14827,13686,0.0,2011-07-23,Hesawa,0,HESAWA,32.985694,-2.734208e+00,Kwa Itob,0,...,hand pump,hand pump,functional,non functional,functional,non functional,functional,functional,3,functional

In [19]:
def mymode(row):
    return row.mode().iloc[0]

df['mode'] = df[pcols].apply(mymode, axis=1)

In [18]:
df[pcols].head().apply(m)

,p0,p1,p2,p3,p4,p5
0,non functional,non functional,functional,functional,functional,functional
1,functional,functional,functional,functional,functional,functional
2,functional,functional,functional,functional,functional,functional
3,non functional,non functional,non functional,non functional,non functional,non functional
4,functional,functional,functional,functional,functional,functional

In [20]:
df.loc[~(df['mode'] == df['status_group'])]

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,waterpoint_type_group,p0,p1,p2,p3,p4,p5,p0_matches,status_group,mode
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,other,non functional,non functional,functional,functional,functional,functional,1,non functional,functional
304,6148,0.0,2013-02-07,Unicef,1315,TWESA,30.496023,-3.619063,Mshenyi Primary School,0,...,communal standpipe,non functional,functional,non functional,non functional,functional,functional,2,non functional,functional
396,4135,0.0,2011-03-14,World Bank,0,DWE,35.352657,-5.178818,Doyo,0,...,communal standpipe,non functional,functional,non functional,non functional,functional,functional,2,non functional,functional
489,48326,0.0,2011-03-25,Government Of Tanzania,1372,DWE,38.397102,-4.925161,Kwamahele Sande,0,...,communal standpipe,non functional,non functional,functional,non functional,functional,functional,2,non functional,functional
1185,20187,250.0,2013-02-18,Norad,1297,NORAD,30.153934,-4.478252,Kwa Mkambati,0,...,communal standpipe,non functional,functional,non functional,functional,non functional,functional,2,non functional,functional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13145,50987,0.0,2011-08-07,Cpps Wat,545,CPPS wat,37.701639,-6.816267,Shuleni,0,...,other,non functional,non functional,functional,functional,functional,non functional,2,non functional,functional
13955,58103,0.0,2011-07-27,Danida,0,DWE,30.535078,-2.482266,Kwabagege,0,...,communal standpipe,functional needs repair,functional needs repair,functional needs repair,functional,functional,functional,2,functional needs repair,functional
14124,36167,0.0,2013-03-21,Danida,1721,DANIDA,34.882931,-11.035340,Kwa Mzee Jolamanusi,0,...,other,functional needs repair,functional needs repair,functional needs repair,functional,functional,functional,2,functional needs repair,functional
14126,62788,0.0,2011-08-17,Rudep,1491,DWE,32.068860,-8.687230,Kwa Hapendeki Katenya,0,...,hand pump,non functional,non functional,non functional,functional,functional,functional,2,non functional,functional
14161,57855,0.0,2012-10-16,Rwssp,0,DWE,32.138027,-3.987195,Mkombozi,0,...,hand pump,non functional,functional,functional,non functional,non functional,functional,2,non functional,functional

In [21]:
df['status_group'] = df['mode']
df[['id', 'status_group']].to_csv("out/manual_2mode-stepthom_submission.csv", index=False)